/**
 * Template Generator Service
 * Generates index.html and data.js files for preview pages
 */

const path = require('path');
const fs = require('fs');

// Path to templates directory
const templatesDir = path.join(__dirname, '../../../templates');

/**
 * Generate preview templates based on creative content
 * @param {Object} options - Generation options
 * @param {string} options.creativeName - Name of the creative
 * @param {string} options.folderPath - Folder path for the preview
 * @param {string} options.description - Creative description
 * @param {string} options.clientName - Client name
 * @param {Array} options.files - Extracted files from ZIP
 * @returns {Promise<Array>} Generated template files
 */
async function generate({ creativeName, folderPath, description, clientName, files }) {
  const templates = [];

  // Find images in the files
  const images = files.filter(f => f.type === 'image');
  
  // Check if there's already an index.html
  const hasExistingHtml = files.some(f => 
    f.path.toLowerCase().endsWith('index.html') ||
    f.path.toLowerCase().endsWith('index.htm')
  );

  // Generate data.js with creative metadata
  const dataJs = generateDataJs({
    creativeName,
    description,
    clientName,
    images,
    files,
  });
  
  templates.push({
    path: 'data.js',
    content: dataJs,
    encoding: 'utf-8',
    type: 'javascript',
  });

  // Only generate index.html if one doesn't exist
  if (!hasExistingHtml) {
    const indexHtml = generateIndexHtml({
      creativeName,
      description,
      clientName,
      images,
    });

    templates.push({
      path: 'index.html',
      content: indexHtml,
      encoding: 'utf-8',
      type: 'html',
    });
  }

  return templates;
}

/**
 * Generate data.js content
 */
function generateDataJs({ creativeName, description, clientName, images, files }) {
  const imageData = images.map(img => ({
    path: img.path,
    name: path.basename(img.path),
  }));

  const fileList = files.map(f => ({
    path: f.path,
    type: f.type,
  }));

  const data = {
    creativeName,
    description: description || '',
    clientName: clientName || '',
    createdAt: new Date().toISOString(),
    images: imageData,
    files: fileList,
  };

  return `/**
 * Creative Preview Data
 * Auto-generated by Ad Preview Staging Tool
 */
const CREATIVE_DATA = ${JSON.stringify(data, null, 2)};

// Export for module environments
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CREATIVE_DATA;
}
`;
}

/**
 * Generate index.html content
 */
function generateIndexHtml({ creativeName, description, clientName, images }) {
  // Try to load custom template
  let template;
  try {
    const templatePath = path.join(templatesDir, 'index.html');
    if (fs.existsSync(templatePath)) {
      template = fs.readFileSync(templatePath, 'utf-8');
    }
  } catch (err) {
    console.log('Using default template');
  }

  // Use default template if custom not found
  if (!template) {
    template = getDefaultTemplate();
  }

  // Replace placeholders
  const html = template
    .replace(/{{CREATIVE_NAME}}/g, escapeHtml(creativeName))
    .replace(/{{DESCRIPTION}}/g, escapeHtml(description || ''))
    .replace(/{{CLIENT_NAME}}/g, escapeHtml(clientName || ''))
    .replace(/{{IMAGES}}/g, generateImageGallery(images))
    .replace(/{{GENERATED_DATE}}/g, new Date().toISOString());

  return html;
}

/**
 * Generate image gallery HTML
 */
function generateImageGallery(images) {
  if (!images || images.length === 0) {
    return '<p class="no-images">No images found in this creative</p>';
  }

  return images.map(img => `
    <div class="gallery-item">
      <img src="${escapeHtml(img.path)}" alt="${escapeHtml(path.basename(img.path))}" loading="lazy">
      <span class="image-name">${escapeHtml(path.basename(img.path))}</span>
    </div>
  `).join('\n');
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text) {
  if (!text) return '';
  const map = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, m => map[m]);
}

/**
 * Get default HTML template
 */
function getDefaultTemplate() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{CREATIVE_NAME}} - Preview</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
      min-height: 100vh;
      color: #fff;
      padding: 40px 20px;
    }
    .container { max-width: 1200px; margin: 0 auto; }
    header {
      text-align: center;
      margin-bottom: 40px;
    }
    h1 {
      font-size: 2.5rem;
      background: linear-gradient(90deg, #00d9ff, #00ff88);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      margin-bottom: 10px;
    }
    .meta {
      color: rgba(255,255,255,0.6);
      font-size: 0.9rem;
    }
    .description {
      margin-top: 15px;
      color: rgba(255,255,255,0.8);
    }
    .gallery {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
      gap: 20px;
    }
    .gallery-item {
      background: rgba(255,255,255,0.05);
      border: 1px solid rgba(255,255,255,0.1);
      border-radius: 12px;
      padding: 15px;
      text-align: center;
    }
    .gallery-item img {
      max-width: 100%;
      height: auto;
      border-radius: 8px;
    }
    .image-name {
      display: block;
      margin-top: 10px;
      font-size: 0.85rem;
      color: rgba(255,255,255,0.5);
      word-break: break-all;
    }
    .no-images {
      text-align: center;
      color: rgba(255,255,255,0.5);
      padding: 40px;
    }
    footer {
      text-align: center;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid rgba(255,255,255,0.1);
      color: rgba(255,255,255,0.4);
      font-size: 0.85rem;
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <h1>{{CREATIVE_NAME}}</h1>
      <p class="meta">{{CLIENT_NAME}}</p>
      <p class="description">{{DESCRIPTION}}</p>
    </header>
    <div class="gallery">
      {{IMAGES}}
    </div>
    <footer>
      <p>Generated on {{GENERATED_DATE}}</p>
      <p>Ad Preview Staging Tool</p>
    </footer>
  </div>
  <script src="data.js"></script>
</body>
</html>`;
}

module.exports = {
  generate,
  generateDataJs,
  generateIndexHtml,
  escapeHtml,
};
