/**
 * Creative Preview Data Template
 * This file is auto-generated by the Ad Preview Staging Tool
 * 
 * CREATIVE_DATA contains metadata and file information about the creative
 */

const CREATIVE_DATA = {
  // Creative name/title
  creativeName: "{{CREATIVE_NAME}}",
  
  // Creative description
  description: "{{DESCRIPTION}}",
  
  // Client name
  clientName: "{{CLIENT_NAME}}",
  
  // Timestamp when the preview was generated
  createdAt: "{{CREATED_AT}}",
  
  // List of images in the creative
  images: [
    // { path: "images/banner.png", name: "banner.png" }
  ],
  
  // List of all files in the creative
  files: [
    // { path: "index.html", type: "html" },
    // { path: "styles.css", type: "css" }
  ]
};

// Export for module environments
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CREATIVE_DATA;
}
